<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Notifications\Messages\MailMessage;

class CombinedFundReportNotification extends Notification
{
    use Queueable;

    private string $facilityName;
    private string $generatedBy;
    private string $generatedAt;
    private string $fileName;
    private string $pdfBinary;

    public function __construct(string $facilityName, string $generatedBy, string $generatedAt, string $fileName, string $pdfBinary)
    {
        $this->facilityName = $facilityName;
        $this->generatedBy = $generatedBy;
        $this->generatedAt = $generatedAt;
        $this->fileName = $fileName;
        $this->pdfBinary = $pdfBinary;
    }

    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $subject = 'Combined Fund Allocation & Management Report - ' . ($this->facilityName ?: 'Facility');

        return (new MailMessage)
            ->subject($subject)
            ->greeting('Hello ' . ($notifiable->firstname ?? 'Finance Officer') . '!')
            ->line('Please find attached the combined Fund Allocation Summary and Fund Management Report for ' . $this->facilityName . '.')
            ->line('Generated by: ' . $this->generatedBy)
            ->line('Generated at: ' . $this->generatedAt)
            ->attachData($this->pdfBinary, $this->fileName, ['mime' => 'application/pdf'])
            ->action('Open Dashboard', url('/staff-dashboard'))
            ->line('This email was sent automatically by AidPoint.');
    }
}